export const productsData = [
    { 
        id: 1, 
        sku: 'BZ-ATS-01', 
        name: 'Application Tracking System', 
        slug: 'application-tracking-system',
        category: 'HR Tech', 
        brand: 'Black Zero',
        shortDescription: 'Streamline your recruitment with our AI-driven ATS. Automate parsing and ranking to find top talent faster.',
        seoTitle: 'AI Application Tracking System | HR Tech by Black Zero',
        metaDescription: 'Streamline your recruitment with Black Zero\'s AI-driven Application Tracking System. Automate resume parsing and rank top talent instantly in the USA & GCC.',
        seoKeywords: ['AI Application Tracking System', 'HR Tech USA', 'Recruitment Automation Software', 'AI ATS'],
        fullDescription: 'The Application Tracking System (ATS) by Black Zero is a comprehensive recruitment solution engineered to modernize how companies hire. In a competitive job market, finding the right talent manually is time-consuming and error-prone. Our ATS automates the most tedious parts of recruitment, including resume parsing, candidate screening, and interview scheduling. By leveraging advanced Artificial Intelligence, the system automatically ranks applicants based on how well their skills match your job descriptions, ensuring your HR team focuses only on the most qualified candidates. The platform also features a collaborative portal where hiring managers can leave feedback, rate candidates, and share notes in real-time, eliminating email clutter. With built-in integration for major job boards like LinkedIn and Indeed, you can post openings with a single click. Furthermore, the advanced analytics dashboard provides deep insights into your hiring pipeline, helping you identify bottlenecks and reduce your time-to-hire significantly. This is the ultimate tool for scaling your workforce efficiently.',
        features: [
            'AI-Powered Resume Parsing',
            'Automated Candidate Ranking',
            'Multi-Job Board Integration',
            'Interview Scheduling Automation',
            'Collaborative Hiring Portals',
            'Advanced Recruitment Analytics'
        ],
        imageSrc: '/products/1.webp',
        imgAltText: 'AI-driven Application Tracking System dashboard showing candidate rankings'
    },
    { 
        id: 2, 
        sku: 'BZ-INV-02', 
        name: 'Company Invoicer', 
        slug: 'company-invoicer',
        category: 'Finance', 
        brand: 'Black Zero',
        shortDescription: 'Automated billing software. Generate professional invoices, track real-time payments, and manage multi-currency accounts.',
        seoTitle: 'Automated Company Invoicer Software | Black Zero',
        metaDescription: 'Simplify billing with Black Zero\'s Company Invoicer. Generate professional invoices, track real-time payments, and manage multi-currency accounts securely.',
        seoKeywords: ['Automated Invoicing Software', 'B2B Billing Software', 'Multi-currency Invoicer', 'Finance Tech USA'],
        fullDescription: 'The Company Invoicer by Black Zero is a robust financial tool designed to simplify billing operations for Small to Medium Enterprises (SMEs). Managing cash flow is critical for business survival, and our software ensures you get paid faster and with less administrative effort. It allows users to generate sleek, professional invoices that are fully compliant with international tax standards. The system excels in automation; you can set up recurring billing profiles for subscription-based clients, ensuring invoices are sent out automatically each month without you lifting a finger. With support for multiple currencies and languages, it is perfect for businesses operating in global markets like Dubai, London, and New York. The real-time dashboard gives you an immediate view of your financial health, highlighting overdue payments and automatically sending polite reminders to clients. Secure, efficient, and easy to use, the Company Invoicer removes the headache from financial management.',
        features: [
            'Customizable Invoice Templates',
            'Recurring Billing Support',
            'Multi-Currency & Multi-Language',
            'Automatic Payment Reminders',
            'Tax Calculation & Compliance',
            'Financial Reporting Dashboard'
        ],
        imageSrc: '/products/2.webp',
        imgAltText: 'Company Invoicer software interface displaying automated billing and payment tracking'
    },
    { 
        id: 3, 
        sku: 'BZ-SEO-03', 
        name: 'SEO Auditor', 
        slug: 'seo-auditor',
        category: 'Marketing', 
        brand: 'Black Zero',
        shortDescription: 'Deep-dive site analysis tool. Identify technical issues, analyze backlinks, and gain insights to outrank competitors.',
        seoTitle: 'Advanced SEO Auditor Tool | Technical Analysis | Black Zero',
        metaDescription: 'Boost your search rankings with Black Zero\'s SEO Auditor. Analyze technical issues, audit backlinks, and outrank competitors with comprehensive insights.',
        seoKeywords: ['SEO Auditor Tool', 'Technical SEO Analysis', 'Backlink Checker', 'Competitor SEO Analysis', 'SEO Software'],
        fullDescription: 'Boost your search engine visibility with the SEO Auditor, a powerful diagnostic tool built for marketers and website owners who are serious about growth. Search Engine Optimization is complex, but our Auditor simplifies it by crawling your entire website to identify technical errors that are hurting your rankings. From broken links and missing meta tags to slow page load speeds, it highlights every issue and provides actionable instructions on how to fix them. Beyond internal health, the tool offers comprehensive competitor analysis, allowing you to spy on the keywords and backlink strategies your rivals are using to win. The platform visualizes data in an intuitive dashboard, making complex metrics easy to understand for stakeholders. For digital agencies, the white-label reporting feature allows you to generate branded, professional PDF reports for your clients in seconds. Drive sustainable organic traffic and ensure your website is perfectly optimized for Google algorithms with SEO Auditor.',
        features: [
            'Technical SEO Crawling',
            'Keyword Ranking Tracker',
            'Backlink Profile Analysis',
            'Competitor Analysis',
            'Page Speed Insights',
            'White-Label Reporting'
        ],
        imageSrc: '/products/3.webp',
        imgAltText: 'SEO Auditor tool dashboard showing website health score and backlink analysis'
    },
    { 
        id: 4, 
        sku: 'BZ-LGS-04', 
        name: 'Lead Generation Software', 
        slug: 'lead-generation-software',
        category: 'Marketing', 
        brand: 'Black Zero',
        shortDescription: 'Find high-quality leads instantly. Use advanced data mining to connect with decision-makers and sync them to your CRM.',
        seoTitle: 'B2B Lead Generation Software & Data Mining | Black Zero',
        metaDescription: 'Supercharge your sales with Black Zero\'s Lead Generation Software. Mine verified B2B contacts, find decision-makers, and sync directly to your CRM.',
        seoKeywords: ['B2B Lead Generation Software', 'Data Mining Tool', 'Verified Business Emails', 'Sales Outreach Automation'],
        fullDescription: 'Supercharge your sales pipeline with the Black Zero Lead Generation Software. In the world of B2B sales, data is power, and this tool gives you access to millions of verified contacts to help you find your next big client. Using advanced data mining algorithms, it scrapes and aggregates public data from professional networks and business directories to find leads that match your specific customer profile. Unlike standard scrapers, our software includes a built-in verification engine that tests email addresses in real-time, ensuring your outreach campaigns have high deliverability and low bounce rates. It seamlessly integrates with popular CRMs like HubSpot and Salesforce, allowing you to export lead lists directly into your sales workflow. Whether you are looking for CEOs in Dubai or IT Managers in London, this software provides the accurate contact information your sales team needs to close deals faster.',
        features: [
            'Targeted Lead Search',
            'Email Verification Engine',
            'LinkedIn Data Extraction',
            'CRM Integration (HubSpot, Salesforce)',
            'Automated Outreach Campaigns',
            'Real-time Data Enrichment'
        ],
        imageSrc: '/products/4.webp',
        imgAltText: 'Lead Generation Software interface showing list of verified business contacts'
    },
    { 
        id: 5, 
        sku: 'BZ-MTH-05', 
        name: 'Laplace Mathematics Equation Solver', 
        slug: 'laplace-math-solver',
        category: 'Education', 
        brand: 'Black Zero',
        shortDescription: 'Computational tool for complex math. Solves differential equations with step-by-step visualization for engineers and researchers.',
        seoTitle: 'Laplace Math Equation Solver | Engineering Tech | Black Zero',
        metaDescription: 'Solve complex differential equations with Black Zero\'s Laplace Math Solver. Get step-by-step visualizations for engineering and academic research.',
        seoKeywords: ['Laplace Equation Solver', 'Engineering Math Software', 'Differential Equation Calculator', 'EdTech AI'],
        fullDescription: 'The Laplace Mathematics Equation Solver is an advanced computational engine designed specifically for the academic and engineering sectors. While traditional calculators provide only the final answer, this software focuses on the "how" and "why," providing detailed, step-by-step breakdowns of complex problems. It specializes in solving differential equations, Laplace transforms, and complex calculus problems commonly faced in electrical engineering and physics. The tool features a powerful graphing engine capable of rendering 2D and 3D visualizations of mathematical models, helping users intuitively understand system behaviors. It supports symbolic computation, ensuring precision for theoretical research. Built with offline capabilities, it is an indispensable companion for students, professors, and researchers who need reliable mathematical modeling without being tethered to the internet. Whether you are designing control systems or studying signal processing, this tool bridges the gap between theory and application.',
        features: [
            'Laplace Transform Calculator',
            'Step-by-Step Solution Steps',
            '2D & 3D Graphing Capabilities',
            'Symbolic Computation',
            'Equation History & Export',
            'Offline Mode Support'
        ],
        imageSrc: '/products/5.webp',
        imgAltText: 'Laplace Math Solver software displaying complex equation solutions and 3D graphs'
    },
    { 
        id: 6, 
        sku: 'BZ-STK-06', 
        name: 'Future Stocks Prediction', 
        slug: 'future-stocks-prediction',
        category: 'Finance', 
        brand: 'Black Zero',
        shortDescription: 'AI market analysis. Use deep learning and sentiment analysis to forecast stock performance and mitigate investment risks.',
        seoTitle: 'AI Future Stocks Prediction Software | Fintech | Black Zero',
        metaDescription: 'Forecast stock market trends with Black Zero\'s AI Future Stocks Prediction tool. Use deep learning and sentiment analysis to maximize your portfolio.',
        seoKeywords: ['AI Stock Prediction', 'Fintech AI Tool', 'Stock Market Forecasting Software', 'Deep Learning Finance'],
        fullDescription: 'Stay ahead of market volatility with Future Stocks Prediction, an AI-driven analytics platform for modern investors. Financial markets are driven by patterns and sentiment, and our software utilizes deep learning neural networks to analyze decades of historical data alongside real-time news feeds. It assesses market sentiment from social media and financial reports to predict short-term and long-term stock movements with remarkable accuracy. The platform is designed for both day traders and long-term investors, offering tools to backtest trading strategies against historical events to see how they would have performed. With customizable risk assessment features, you can adjust the sensitivity of the predictions to match your investment style. This is not just a charting tool; it is a predictive engine that empowers you to make data-backed decisions, reducing reliance on guesswork and maximizing your portfolio returns.',
        features: [
            'AI-Driven Price Forecasting',
            'Sentiment Analysis',
            'Historical Data Backtesting',
            'Real-Time Market Alerts',
            'Portfolio Risk Assessment',
            'Customizable Indicators'
        ],
        imageSrc: '/products/6.webp',
        imgAltText: 'Future Stocks Prediction platform showing AI-driven market forecast charts'
    },
    { 
        id: 7, 
        sku: 'BZ-EML-07', 
        name: 'Email Finder', 
        slug: 'email-finder',
        category: 'Sales Tools', 
        brand: 'Black Zero',
        shortDescription: 'Locate verified professional emails instantly. Reduce bounce rates and connect with key decision-makers efficiently.',
        seoTitle: 'B2B Email Finder Tool | Verified Lead Contacts | Black Zero',
        metaDescription: 'Locate and verify professional email addresses instantly with Black Zero\'s Email Finder. Reduce bounce rates and connect with B2B decision-makers.',
        seoKeywords: ['B2B Email Finder', 'Email Verification Tool', 'Sales Outreach Software', 'Lead Contact Finder'],
        fullDescription: 'The Email Finder by Black Zero is the ultimate tool for outreach specialists and marketers looking to build high-quality contact lists. Connecting with decision-makers is often the hardest part of sales, but this tool removes the barrier by locating verified professional email addresses in seconds. Simply enter a prospect name and their company domain, and our system scans multiple trusted databases to retrieve accurate contact details. We prioritize data hygiene, meaning every email found is verified in real-time to ensure it is active, drastically reducing your bounce rates and protecting your sender reputation. The tool supports bulk processing, allowing you to upload a CSV of prospects and get thousands of emails at once. It also features a Chrome extension for seamless integration while browsing LinkedIn, making it the fastest way to grow your sales pipeline.',
        features: [
            'Domain Search',
            'Bulk Email Search',
            'Real-Time Verification',
            'Chrome Extension Integration',
            'Export to CSV',
            'API Access'
        ],
        imageSrc: '/products/7.webp',
        imgAltText: 'Email Finder tool extracting verified contact details for sales outreach'
    },
    { 
        id: 8, 
        sku: 'BZ-PHN-08', 
        name: 'Phone Number Finder', 
        slug: 'phone-number-finder',
        category: 'Sales Tools', 
        brand: 'Black Zero',
        shortDescription: 'Find direct dial numbers for prospects. Validates connectivity and adheres to compliance standards for sales teams.',
        seoTitle: 'B2B Phone Number Finder | Direct Dial Contacts | Black Zero',
        metaDescription: 'Find verified direct dial phone numbers for B2B prospects. Use Black Zero\'s Phone Number Finder to bypass gatekeepers and accelerate your sales cycle.',
        seoKeywords: ['B2B Phone Number Finder', 'Direct Dial Search Tool', 'Sales Cold Calling Software', 'Lead Phone Number Finder'],
        fullDescription: 'Close the gap between you and your prospects with the Phone Number Finder. In high-stakes sales, getting a prospect on the phone is half the battle. This tool enables your team to bypass gatekeepers and switchboards by discovering direct mobile and landline numbers for professionals globally. We take data compliance seriously; the system includes an automatic Do Not Call (DNC) registry check to ensure your cold calling campaigns adhere to legal regulations. Before delivering a number, the software pings the carrier network to validate connectivity, ensuring you dont waste time dialing dead lines. Ideal for high-volume telemarketing teams and headhunters, this tool enriches your CRM with the most valuable piece of contact data available: a direct line to your next customer.',
        features: [
            'Direct Dial Search',
            'Global Number Coverage',
            'DNC (Do Not Call) Registry Check',
            'Carrier Lookup',
            'Contact List Enrichment',
            'Mobile vs Landline Identification'
        ],
        imageSrc: '/products/8.webp',
        imgAltText: 'Phone Number Finder interface showing direct dial search results for sales'
    }
];